FROM quay.io/pypa/manylinux_2_28_x86_64

RUN dnf install -y glibc-static

WORKDIR /io/external
RUN mkdir /io/external/gromacs_installed
ENV GMX_SRC=/io/external/gromacs-2025.0
ENV GMX_PATH=/io/external/gromacs_installed

RUN curl -L -O https://ftp.gromacs.org/gromacs/gromacs-2025.0.tar.gz && tar -zxf gromacs-2025.0.tar.gz
WORKDIR /io/external/gromacs-2025.0/build
RUN cmake .. -DGMX_SIMD=SSE2 -DGMX_GPU=off -DGMXAPI=OFF -DGMX_INSTALL_LEGACY_API=on -DGMX_FFT_LIBRARY=fftpack \
             -DCMAKE_INSTALL_PREFIX=${GMX_PATH} -DGMX_PREFER_STATIC_LIBS=ON -DGMX_OPENMP=OFF -DBUILD_SHARED_LIBS=OFF
RUN make -j10
RUN make install

WORKDIR /build
RUN cmake -DGMX_PATH=${GMX_PATH} -DGMX_SRC=${GMX_SRC} -DBUILD_STATIC=ON .. && make && make install

CMD ["do_x3dna", "-h"]
