name: Build-Release

on:
  push:
    tags:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v4
        with:
          run: podman build --file Dockerfile.static -v `pwd`:/io --tag my-image-name:$(date +%s) . 

      - name: Release the binary
        uses: softprops/action-gh-release@v2
        with:
          files: build/do_x3dna/do_x3dna
