name: Build-Release

on:
  push:
    tags:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: podman build --file Dockerfile.static -v `pwd`:/io --tag my-image-name:$(date +%s) . 

      - name: Release the binary
        uses: softprops/action-gh-release@v2
        with:
          files: build/do_x3dna_x86_64.tar.gz
